from django.conf import settings

DATABASE_BACKEND = getattr(settings, 'SGAOAUTH_DATABASE_BACKEND', 'sqlalchemy')
SESSION_BACKEND = getattr(settings, 'SGAOAUTH_DATABASE_BACKEND', 'django')

NONCE_CLASS = getattr(settings, 'SGAOAUTH_NONCE_CLASS', '')
CONSUMER_TOKEN_CLASS = getattr(settings, 'SGAOAUTH_CONSUMER_TOKEN_CLASS', '')
REQUEST_TOKEN_CLASS = getattr(settings, 'SGAOAUTH_REQUEST_TOKEN_CLASS', '')
ACCESS_TOKEN_CLASS = getattr(settings, 'SGAOAUTH_ACCESS_TOKEN_CLASS', '')

GET_NONCE = getattr(settings, 'SGAOAUTH_GET_NONCE', '')
GET_CONSUMER_TOKEN = getattr(settings, 'SGAOAUTH_GET_CONSUMER_TOKEN', '')
GET_REQUEST_TOKEN = getattr(settings, 'SGAOAUTH_GET_REQUEST_TOKEN', '')
GET_ACCESS_TOKEN = getattr(settings, 'SGAOAUTH_GET_ACCESS_TOKEN', '')
SAVE_NONCE = getattr(settings, 'SGAOAUTH_SAVE_NONCE', '')
SAVE_CONSUMER_TOKEN = getattr(settings, 'SGAOAUTH_SAVE_CONSUMER_TOKEN', '')
SAVE_REQUEST_TOKEN = getattr(settings, 'SGAOAUTH_SAVE_REQUEST_TOKEN', '')
SAVE_ACCESS_TOKEN = getattr(settings, 'SGAOAUTH_SAVE_ACCESS_TOKEN', '')
REMOVE_NONCE = getattr(settings, 'SGAOAUTH_REMOVE_NONCE', '')
REMOVE_CONSUMER_TOKEN = getattr(settings, 'SGAOAUTH_REMOVE_CONSUMER_TOKEN', '')
REMOVE_REQUEST_TOKEN = getattr(settings, 'SGAOAUTH_REMOVE_REQUEST_TOKEN', '')
REMOVE_ACCESS_TOKEN = getattr(settings, 'SGAOAUTH_REMOVE_ACCESS_TOKEN', '')

SET_TO_SESSION = getattr(settings, 'SGAOAUTH_SET_TO_SESSION', '')
GET_FROM_SESSION = getattr(settings, 'SGAOAUTH_GET_FROM_SESSION', '')
REMOVE_FROM_SESSION = getattr(settings, 'SGAOAUTH_REMOVE_FROM_SESSION', '')
